---
name: Quality Checks

on: [push]

jobs:
  test-lint:
    name: Test/Lint/Format
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "pytest app"
      - name: Format
        run: docker-compose run --rm app sh -c "black app && isort app"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8 app"
